name: zebrrasea
version: 11.0.0
confinement: strict
base: core22
# Required but managed manually via Snapcraft dashboard
summary: summary
description: description
slots:
  dbus-zebrrasea:
    interface: dbus
    bus: session
    name: app.zebrrasea.zebrrasea
apps:
  zebrrasea:
    command: zebrrasea
    extensions:
    - gnome
    plugs:
    - home
    - network
    slots:
    - dbus-zebrrasea
parts:
  zenity:
    plugin: nil
    stage-packages:
    - zenity
  zebrrasea:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
