blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Support via Discord
    url: https://www.zagreus.app/discord
    about: Request new features and get support from the community
  - name: Support via GitHub Discussions
    url: https://github.com/JagandeepBrar/zagreus/discussions
    about: Ask questions and discuss with other community members
  - name: Support via Reddit
    url: https://www.zagreus.app/reddit
    about: Ask the developer and other redditors for support and setup related topics
