# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zagreus-notifications"
primary_region = "ord"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"
  # Redis (using Upstash.com)
  REDIS_HOST = "literate-burro-9541.upstash.io"
  REDIS_PORT = "6379"
  REDIS_USE_TLS = "true"
  REDIS_USER = "default"
  # Database (using Supabase direct connection)
  DB_HOST = "db.unrzdubozarzulnlbdqe.supabase.co"
  DB_PORT = "5432"
  DB_NAME = "postgres"
  DB_USER = "postgres"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 5
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256