name: zagreus
version: 11.0.0
confinement: strict
base: core22
# Required but managed manually via Snapcraft dashboard
summary: summary
description: description
slots:
  dbus-zagreus:
    interface: dbus
    bus: session
    name: app.zagreus.zagreus
apps:
  zagreus:
    command: zagreus
    extensions:
    - gnome
    plugs:
    - home
    - network
    slots:
    - dbus-zagreus
parts:
  zenity:
    plugin: nil
    stage-packages:
    - zenity
  zagreus:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
